Bootstrap: docker
From: ubuntu:16.04

%post
    cd /home
    apt-get -y update
    apt-get install -y --no-install-recommends git gcc make g++ libboost-all-dev liblzma-dev libbz2-dev ca-certificates zlib1g-dev curl unzip autoconf vim wget time bzip2 nano unzip libpthread-stubs0-dev

    wget https://cmake.org/files/v3.9/cmake-3.9.5-Linux-x86_64.sh
    mkdir /opt/cmake
    sh cmake-3.9.5-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
    ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
    rm cmake-3.9.5-Linux-x86_64.sh

    curl -o /usr/local/bin/jq http://stedolan.github.io/jq/download/linux64/jq
    chmod +x /usr/local/bin/jq

    yes | apt-get install software-properties-common
    add-apt-repository ppa:deadsnakes/ppa
    apt-get update

    yes | apt-get install python3.6
    
    CONDA_PATH="/root/miniconda3/bin"
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    chmod +x Miniconda3-latest-Linux-x86_64.sh
    printf "\nyes\n\nyes\n" | ./Miniconda3-latest-Linux-x86_64.sh -p $CONDA_PATH
    
    yes | /root/miniconda3/bin/bin/conda install -c bioconda -c conda-forge snakemake
    rm Miniconda3-latest-Linux-x86_64.sh
    
    wget https://github.com/01org/tbb/releases/download/2018_U4/tbb2018_20180411oss_lin.tgz
    tar zxf tbb2018_20180411oss_lin.tgz
    rm tbb2018_20180411oss_lin.tgz
    cd tbb2018_20180411oss
    cp -r include /usr/local
    cp -r lib/intel64/gcc4.7/* /usr/local/lib
    cd ..
    rm -rf tbb2018_20180411oss
    
    git clone https://github.com/fataltes/TwoPaCo.git
    
    cd TwoPaCo
    git checkout pufferize
    mkdir build
    cd build
    cmake ../src
    make
    cd ..
    cd ..

    git clone https://github.com/COMBINE-lab/pufferfish.git
    
    cd pufferfish
    git clone https://github.com/simongog/sdsl-lite.git
    cd sdsl-lite
    ./install.sh ../
    cd ..

    git checkout AGAMEMNON
    mkdir build
    cd build
    cmake ../
    make
    cd ..
    cd ..
    
    mkdir hisat2
    cd hisat2
    wget http://ccb.jhu.edu/software/hisat2/dl/hisat2-2.1.0-Linux_x86_64.zip
    unzip hisat2-2.1.0-Linux_x86_64.zip
    rm -rf hisat2-2.1.0-Linux_x86_64.zip
    cd ..
    
    mkdir AGAMEMNON
    cd AGAMEMNON
    git clone https://github.com/ivlachos/agamemnon.git
    cd agamemnon
    git checkout master
    cd ..
    cp -a /home/AGAMEMNON/agamemnon/. /home/AGAMEMNON/
    rm -rf /home/AGAMEMNON/agamemnon
    
    mkdir binaries
    cd binaries
    mkdir pufferfish
    mkdir TwoPaco
    mkdir hisat2-2.1.0
    cd ..
    cd ..
    cp -a /home/pufferfish/. /home/AGAMEMNON/binaries/pufferfish
    cp -a /home/TwoPaCo/. /home/AGAMEMNON/binaries/TwoPaCo
    cp -a /home/hisat2/. /home/AGAMEMNON/binaries/hisat2-2.1.0
    rm -rf pufferfish
    rm -rf TwoPaCo
    rm -rf hisat2
    
    chmod +x /home/AGAMEMNON/scripts/downloadTaxonomy.sh
    chmod +x /home/AGAMEMNON/scripts/editYaml.py
    chmod +x /home/AGAMEMNON/scripts/getTaxonomy.py
    chmod +x /home/AGAMEMNON/scripts/indexSize.py
    chmod +x /home/AGAMEMNON/scripts/single_cell-demultiplex.py
    chmod +x /home/AGAMEMNON/scripts/accessions2taxids.py
    chmod +x /home/AGAMEMNON/scripts/taxonomy.sh
    
    sed -i 's#"pufferfish":"/home/pufferfish",#"pufferfish":"/home/AGAMEMNON/binaries/pufferfish",#g' /home/AGAMEMNON/binaries/pufferfish/config.json && \
    sed -i 's#"twopaco":"/home/TwoPaCo",#"twopaco":"/home/AGAMEMNON/binaries/TwoPaCo",#g' /home/AGAMEMNON/binaries/pufferfish/config.json

%environment
    export PUFFERFISH_VERSION=0.9.0
